import type { ToolModule, McpToolDefinition, McpToolResult, ToolVisibility } from '../../types';
import { createAgent, updateAgent } from './handlers';
import type { CreateAgentArgs, UpdateAgentArgs } from './handlers';

export class AgentModule implements ToolModule {
  id = 'agent';
  toolVisibility: ToolVisibility = 'all-configured';

  isEnabled(): boolean {
    return true;
  }

  getTools(): McpToolDefinition[] {
    return [
      {
        name: 'agent_create',
        description:
          'Create a new Claude Gateway agent with a workspace and channel configuration. The gateway hot-adds the agent without requiring a restart.',
        inputSchema: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              description:
                'Agent ID: starts with a letter, 2-32 chars, letters/numbers/underscores/hyphens. Stored lowercase.',
            },
            description: {
              type: 'string',
              description:
                "One-paragraph description of the agent's role, personality, and capabilities.",
            },
            channel: {
              type: 'string',
              enum: ['telegram', 'discord'],
              description: 'Primary channel for this agent.',
            },
            bot_token: {
              type: 'string',
              description:
                'Bot token. Telegram: 123456789:AAHfiq... Discord: MTAxMTk....AAAA.xxx.',
            },
            telegram_user_id: {
              type: 'string',
              description:
                'Telegram numeric chat_id (6–15 digits, e.g. "997170033"). ONLY pass here when channel=telegram. IMPORTANT: If you are responding to a Telegram message, use the sender chat_id from the inbound message context directly — do NOT ask the user for it. NEVER put a Discord Snowflake (17–19 digits) here.',
            },
            discord_user_id: {
              type: 'string',
              description:
                'Discord Snowflake user ID (17–19 digits, e.g. "932651528878194749"). ONLY pass here when channel=discord. IMPORTANT: If you are responding to a Discord message, use the sender user ID from the inbound message context directly — do NOT ask the user for it. NEVER put a Telegram chat_id (6–15 digits) here.',
            },
            dm_policy: {
              type: 'string',
              enum: ['open', 'allowlist', 'pairing'],
              description: 'DM access policy. Default: allowlist.',
            },
            model: {
              type: 'string',
              description: 'Claude model to use. Default: claude-sonnet-4-6.',
            },
            signature_emoji: {
              type: 'string',
              description: 'Optional emoji the agent uses as a signature.',
            },
            agents_md: {
              type: 'string',
              description:
                'Full AGENTS.md content (AI-generated by caller). If omitted, a stub is created from description.',
            },
            soul_md: {
              type: 'string',
              description: 'Full SOUL.md content. If omitted, an empty stub is created.',
            },
            user_md: {
              type: 'string',
              description: 'Full USER.md content. If omitted, an empty stub is created.',
            },
          },
          required: ['id', 'description', 'channel', 'bot_token'],
          additionalProperties: false,
        },
      },
      {
        name: 'agent_update',
        description:
          'Update an existing agent: add a new channel, remove a channel, or update a workspace file.',
        inputSchema: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              description: 'Agent ID to update.',
            },
            action: {
              type: 'string',
              enum: ['add_channel', 'remove_channel', 'update_workspace_file'],
              description: 'Operation to perform.',
            },
            channel: {
              type: 'string',
              enum: ['telegram', 'discord'],
              description: 'Channel (required for add_channel and remove_channel).',
            },
            bot_token: {
              type: 'string',
              description: 'Bot token (required for add_channel).',
            },
            telegram_user_id: {
              type: 'string',
              description:
                'Telegram numeric chat_id (6–15 digits). add_channel only, when channel=telegram. IMPORTANT: If responding to a Telegram message, use the sender chat_id directly — do NOT ask the user for it. NEVER put a Discord Snowflake (17–19 digits) here.',
            },
            discord_user_id: {
              type: 'string',
              description:
                'Discord Snowflake user ID (17–19 digits). add_channel only, when channel=discord. IMPORTANT: If responding to a Discord message, use the sender user ID directly — do NOT ask the user for it. NEVER put a Telegram chat_id (6–15 digits) here.',
            },
            dm_policy: {
              type: 'string',
              enum: ['open', 'allowlist', 'pairing'],
              description: 'DM policy for the new channel (add_channel only). Default: allowlist.',
            },
            filename: {
              type: 'string',
              description:
                'Workspace file to write (update_workspace_file only). E.g. "SOUL.md". No path traversal allowed.',
            },
            content: {
              type: 'string',
              description: 'New file content (update_workspace_file only).',
            },
          },
          required: ['id', 'action'],
          additionalProperties: false,
        },
      },
    ];
  }

  async handleTool(name: string, args: Record<string, unknown>): Promise<McpToolResult> {
    try {
      let result: string;

      if (name === 'agent_create') {
        result = await createAgent(args as unknown as CreateAgentArgs);
      } else if (name === 'agent_update') {
        result = await updateAgent(args as unknown as UpdateAgentArgs);
      } else {
        return {
          content: [{ type: 'text', text: `Unknown tool: ${name}` }],
          isError: true,
        };
      }

      return { content: [{ type: 'text', text: result }] };
    } catch (err) {
      return {
        content: [{ type: 'text', text: (err as Error).message }],
        isError: true,
      };
    }
  }
}
